// <auto-generated />
namespace DatabaseLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class SPRemoteEvents3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SPRemoteEvents3));
        
        string IMigrationMetadata.Id
        {
            get { return "202107222021382_SPRemoteEvents3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
